# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: OxO WTF!!!
email: OxOWTFOxO@Gmail.com
tagline: 魔幻的世界
author: 鲁迅、闰土和猹
description: >- # this means to ignore newlines until "baseurl:"
  我素不知道天下有这许多新鲜事：<br>
  海边有如许五色的贝壳；<br>
  西瓜有这样危险的经历，<br>
  我先前单知道它在水果店里出卖罢了。
disqus:
  shortname: oxowtf

paginate: 5

baseurl: "" # the subpath of your site, e.g. /blog
url: https://OxO.WTF # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
#github_username:  8solo
avatar: /avatar.jpeg
cover_image: /img2.jpeg

# Build settings
theme: minima
plugins:
  - jekyll-feed
  # - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  # - not-pure-poole

# remote_theme: vszhub/not-pure-poole

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
